# Generated by Django 3.2.9 on 2023-02-02 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=122)),
                ('describtion', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='profileimg')),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('type', models.CharField(max_length=122)),
                ('describtion', models.TextField()),
                ('price', models.CharField(max_length=122)),
                ('image', models.ImageField(blank=True, upload_to='profileimg')),
            ],
        ),
    ]
